"""add phone and contact preferences

Revision ID: 197a250c1446
Revises: f7874b2bbad0
Create Date: 2026-10-03 13:59:59.643674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197a250c1446'
down_revision: Union[str, Sequence[str], None] = 'f7874b2bbad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('phone', sa.String(length=16), nullable=True))
    op.add_column('leads', sa.Column('preferred_contact', sa.String(length=20), server_default=sa.text("'email'"), nullable=False))
    op.add_column('leads', sa.Column('whatsapp_consent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('leads', sa.Column('whatsapp_consent_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
    op.drop_column('leads', 'whatsapp_consent_at')
    op.drop_column('leads', 'whatsapp_consent')
    op.drop_column('leads', 'preferred_contact')
    op.drop_column('leads', 'phone')
    # ### end Alembic commands ###
