"""add enquiry AI analysis

Revision ID: aa43ef13f10f
Revises: 197a250c1446
Create Date: 2026-10-03 23:25:57.328942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa43ef13f10f'
down_revision: Union[str, Sequence[str], None] = '197a250c1446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('leads', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('ai_prompt_version', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('ai_analysed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'ai_analysed_at')
    op.drop_column('leads', 'ai_prompt_version')
    op.drop_column('leads', 'ai_model')
    op.drop_column('leads', 'ai_analysis')
    # ### end Alembic commands ###
